# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0be7c5e603f3d8739ab166408ff350a36ae6317dd5773dbe63689a1f32413eea16a4b66fc8a979f880c8c6cd5776182bce7b38f1458fea723a569dca55af8df6

test:
  secret_key_base: c42464c2b2c43c701b653c1f37b003b6d3d842e7caba4b79a606c06062b03dfd7c45d824bb183dfafed14de7edb80a127609967c28777aa9f4be0352933b3476

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
